export const negativePolarity = {
	asertividad: 0.8,
	'autoconciencia emocional': 0.8,
	autoestima: 0.5,
	'desarrollar y estimular a los demás': 1,
	empatía: 0.3,
	'autocontrol emocional': 1,
	influencia: 0.8,
	liderazgo: 0.5,
	optimismo: 0.3,
	'relación social': 0.5,
	'colaboración y cooperación': 0.5,
	'comprensión organizativa': 0.5,
	'conciencia crítica': 0.8,
	'desarrollo de las relaciones': 0.5,
	'tolerancia a la frustración': 0.5,
	'comunicacion asertiva': 1,
	'manejo de conflictos': 0.5,
	'motivación de logro': 0.3,
	'percepción y comprensión emocional': 0.5,
	violencia: 1,
};
