export const positivePolarity = {
	asertividad: 1,
	'autoconciencia emocional': 1,
	autoestima: 1,
	'desarrollar y estimular a los demás': 1,
	empatía: 1.2,
	'autocontrol emocional': 1,
	influencia: 1,
	liderazgo: 1,
	optimismo: 1.2,
	'relación social': 1,
	'colaboración y cooperación': 1,
	'comprensión organizativa': 1,
	'conciencia crítica': 1,
	'desarrollo de las relaciones': 1,
	'tolerancia a la frustración': 1,
	'comunicacion asertiva': 1,
	'manejo de conflictos': 1,
	'motivación de logro': 1.2,
	'percepción y comprensión emocional': 1,
	violencia: 0.4,
};
